# Generated by Django 4.1.3 on 2022-12-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_item_list_delete_account_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
