# Generated by Django 4.1.3 on 2023-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_list_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
